### ISSUE TITLE
Checks for under bridge don't match with pf2e Rules

### ISSUE THREAD

**Issue by ChasarooniZ** [tianevitt/tianzes-otari-extras#9]
![image](https://github.com/tianevitt/tianzes-otari-extras/assets/79132112/99c7ee6d-96f8-4e1c-9546-5e3be1fb449a)
Resisting the water would most likely fall under a [swimming check](https://2e.aonprd.com/Actions.aspx?ID=2381)
and fishing individually doesn't really make sense as subsistance as that is more of a downtime activity.

**Comment by tianevitt** [comment]
Hey there, thanks for cathing the issue with the swimming check. I'll fix it in the next update.
As for the fishing activity, I was basically trying to bring this description to life (from Abomination Vaults):
![image](https://github.com/tianevitt/tianzes-otari-extras/assets/89922402/7e60b0d0-bfdd-4f48-99eb-e2fbdb554dd6)

**Comment by tianevitt** [comment]
Fixed with 1.2.0. Thanks!
